### ISSUE TITLE
 Its not working((( and your demo not working too?

### ISSUE THREAD

**Issue by vladryjoff** [vincentorback/WebP-images-with-htaccess#11]
Your .htaccess solution not working on my local machine, my VPS, and your demo not working to... vincentorback.github.io/webp-images-with-htaccess/ 
<img width="1440" alt="chrome, macOS" src="https://user-images.githubusercontent.com/56701144/86739329-9dc76680-c057-11ea-85a3-8961085d0f8d.png">
How can i fix it? thank you!

**Comment by vincentorback** [comment]
I’ve updated the demo page, it couldnt work since github-pages doesnt support .htaccess, my bad!
[https://webp.vincentorback.se](https://webp.vincentorback.se/)

Does that work for you?

**Comment by ezetojo** [comment]
> I’ve updated the demo page, it couldnt work since github-pages doesnt support .htaccess, my bad!
> [https://webp.vincentorback.se](https://webp.vincentorback.se/)
> 
> Does that work for you?

still loading jpgs for me...

**Comment by vincentorback** [comment]
> still loading jpgs for me...
@ezetojo does the demo load jpgs for you or does the code in the repo?

**Comment by hiasl** [comment]
works for me! it requests jpegs but loads webp. very sexy for bg images, where all other solutions just work with JS.

**Comment by kastnerp** [comment]
Your demo works for me, however, if I clone your repo to my webspace it loads jpgs in my case.

**Comment by vincentorback** [comment]
@kastnerp are you running a server that executes the .htaccess? If yes, what browser/OS/setup are you running?

**Comment by kastnerp** [comment]
I am running Apache/2.4.39 (Unix) on CentOS Linux release 7.9.2009 (Core). I am not an expert in .htaccess snippets but I found that [this example](https://www.modified-shop.org/forum/index.php?topic=40006.msg361783#msg361783) worked for me for your first two inline images. However, the bg image in the div container [still](https://pkastner.uber.space/webp-test/) doesn't how up. In terms of browsers, I tested with both the latest version of Edge and Firefox.

**Comment by vincentorback** [comment]
@kastnerp  the background image problem looks like a css url() path problem. You can fix it here by adding a dot before /images:
```
0 100% / cover transparent no-repeat url('./images/image1.jpg')
```

Im not a .htaccess expert either but I'll be sure to check out the example that worked for you.
