### ISSUE TITLE
If you can, use the <picture>-element instead of this solution!

### ISSUE THREAD

**Issue by joacim-boive** [vincentorback/WebP-images-with-htaccess#3]
So the obvious question is why is that the preferred solution?

Does the .htaccess implementation come with any drawbacks like worse performance? Server overhead?

Or is it just a matter of best practices?

**Comment by joacim-boive** [comment]
Ok, I did notice now that you send a 302 redirect, so that will have a performance hit.

Anything else I'm missing?

**Comment by vincentorback** [comment]
Yeah the 302-is the biggest one. Then I'm just guessing that tinkering with the .htaccess should be avoided when you can use the picture element instead. My main thought was just to suggest best practice :+1:

**Comment by joacim-boive** [comment]
Ok, thanks for the input!
