### ISSUE TITLE
How do I make it scan every image?

### ISSUE THREAD

**Issue by nickdesjardins** [vincentorback/WebP-images-with-htaccess#6]
It seems like as soon as it sees one image.jpg that has an image.webp it assumes every other jpg has a webp counterpart and tries to show everyOther.jpg to everyOther.webp but what if users (from a blog let's say) add a picture.jpg then it tries to show the picture.webp and it breaks.

**Comment by vincentorback** [comment]
Hmm it works for me (tested in Chrome and Firefox). Webp files are only served if available that is and if not the jpg is served.

Are you just using `<img src="">` and no `srcset` or `<picture>`?

**Comment by nickdesjardins** [comment]
I'm just using <img src=""> do I really need to change to srcset or picture for my whole website?

**Comment by vincentorback** [comment]
No no I was just wondering if you did. So when you don’t have a corresponding webp the image breaks? Do you have something live I can check out?

This works fine for me so I’m not sure what’s wrong.
