### ISSUE TITLE
Hmm not working?

### ISSUE THREAD

**Issue by JayHoltslander** [vincentorback/WebP-images-with-htaccess#7]
I have this code in my .htaccess but Chrome continues to be served [the jpg](https://jay.holtslander.ca/img/jay-aqua.jpg) image instead of [the webp file](https://jay.holtslander.ca/img/jay-aqua.jpg.webp). (Background image)

Thoughts?

**Comment by vincentorback** [comment]
Are you hosting your .htaccess and code on an Apache server?

Sometimes it might look as if a jpg is serverd. As you can see the file name is still image.jpg but the actuall file served is the webp:
![Screenshot 2019-05-03 kl  16 18 24](https://user-images.githubusercontent.com/1780492/57143545-60b27500-6dbf-11e9-87da-7a3cc6ecd7d1.jpg)

**Comment by JayHoltslander** [comment]
Apache with Nginx as a proxy. (ServerPilot.io config)

**Comment by vincentorback** [comment]
Hmm not sure whats wrong.. Maybe you can try and see what happens if you host just the demo included in this repo?
