### ISSUE TITLE
REQUEST_image enviroment variable never set

### ISSUE THREAD

**Issue by echu2013** [vincentorback/WebP-images-with-htaccess#9]
https://github.com/vincentorback/WebP-images-with-htaccess/blob/8796e0fab57442cc1fa546f9d3d2a76f32fe2484/.htaccess#L3
I don`t know why but this is not working for me with **Apache/2.4.43**

**This doest work for me:**
``SetEnvIf Request_URI "\.(jpeg|jpg|png)$" ` REQUEST_image `
Optional "?" is valid regex but my apache does not match anything at all with this.

Thank you for this code which was greatly useful for me!

**Comment by vincentorback** [comment]
resolved by #10
